### ISSUE TITLE
parameter question

### ISSUE THREAD

**Issue by jcardel** [vchrisb/Isilon-POSH#11]
Hi, and thanks for making this awesome Module.
I have a question as to how to define the parameter object for the cmd'let New-Isijobs.
Specifically, I need to use this for permissionrepair, and the -prepair_params, I do not know what notation to type the parameters.
the example I would love to see how you convert is this:
isi job jobs start --type=permissionrepair --mode=inherit --template=/ifs/data/path1 --paths=/ifs/data/path2

It would look like this:
New-isiJobs -type permissionrepair -paths /ifs/data/path2 -prepair_params ??

I have tried looking around, but nobody seems to have posted anything on this, and checking the module or help, doesn't really help me ;)

Thanks in advance.

Oh and mark this a questions please.

**Comment by jcardel** [comment]
Ok i found the solution myself, sorry for my ignorance, examples would have helped ;)
I did: $ged=@{mode="inherit";template="/path"}
and then New-isiJobs -type permissionrepair -paths /ifs/data/path -prepair_params $ged

And all is well ;)

**Comment by vchrisb** [comment]
great! :) I'll add you example to the Readme.
Thank you!
