### ISSUE TITLE
Set-isiSyncPolicy -Force ?

### ISSUE THREAD

**Issue by jcardel** [vchrisb/Isilon-POSH#12]
To "force" this command to run on a number of sync-policy objects, using the -Confirm:$false or -Force does not do what is supposed to. If I exclude it, everything works fine, but I have to confirm it. 
Like: 
Confirm
Are you sure you want to perform this action?
Performing the operation "Set-isiSyncPolicyv1" on target "nfs_aucms".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "Y"):

But setting "$ConfirmPreference" to "low", works too, just for the session that is okay, but maybe not the best idea ever.

Set-isiSyncPolicy -name $name -source_network $null -target_host xxxx.xxx.xxx -target_snapshot_archive $false -Force

Gives this error:
Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
    + CategoryInfo          : InvalidArgument: (:) [Send-isiAPI], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Send-isiAPI

Just saying, otherwise i love you Module, using it all the time ;)

Thanks!

**Comment by vchrisb** [comment]
Hey @jcardel,

I've tried to run you command and it worked for me.
It has to be related to something else. Not sure where the error comes from. `Send-isiAPI` does not have a `Message` parameter.

**Comment by jcardel** [comment]
Hi Chris, sorry for the delay in response.

Maybe it has something to do with environment, but I have seen as a general error if I do something wrong when using the module, that gives that error message;
"Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported."

I have seen it several times, when I pass a wrong parameter to any of the modules set-* cmd'lets,
When/if i see it again, I will try to capture some more info.
