### ISSUE TITLE
Time object format

### ISSUE THREAD

**Issue by jcardel** [vchrisb/Isilon-POSH#13]
I have been trying to figure out what timestamps the Isilon-Posh is returning, and it is not anything I can convert to normal date-time object, at least not so far.
Like a snapshot view taken with get-isisnapshot, the value in "created", I simply cannot figure out the right format. 

A get-member tells me the value is int.
created        NoteProperty int created=1479662178

Do you have a hint as to how to convert this to a datetime object? or just format it correctly.

If this place had a forum I would have asked there, so sorry in advance for making this an issue.

**Comment by hershsa** [comment]
The value is unix/epoch time. Number of seconds from 1/1/1970. Here's a quick snippet I've used:

`
$create_time = $snapshot.created
$orgin = New-Object -Type DateTime -ArguementList 1970, 1, 1, 0, 0, 0, 0
$create_time_human = $orgin.AddSeconds($create_time)

#Account for daylight savings if it matters to you
$tz = Get-CimInstance win32_timezone
$create_time_local = $create_time_human.AddMinutes(($tz.Bias)-($tz.DaylightBias))
`

**Comment by jcardel** [comment]
Perfect, thanks a lot. I should probably have figured that out myself, but was eluding me ;-)

Happy coding,
Johan

On May 15, 2017 13:27, hershsa <notifications@github.com> wrote:

The value is unix/epoch time. Number of seconds from 1/1/1970. Here's a quick snippet I've used:

`
$create_time = $snapshot.created
$orgin = New-Object -Type DateTime -ArguementList 1970, 1, 1, 0, 0, 0, 0
$create_time_human = $orgin.AddSeconds($create_time)

#Account for daylight savings if it matters to you
$tz = Get-CimInstance win32_timezone
$create_time_local = $create_time_human.AddMinutes(($tz.Bias)-($tz.DaylightBias))
`
