### ISSUE TITLE
Send-isiAPI : The property 'errors' cannot be found on this object. Verify that the property exists.

### ISSUE THREAD

**Issue by kbakk** [vchrisb/Isilon-POSH#18]
If you try to set an object (e.g. Set-isiClusterOwner) and don't actually change any properties, you'll receive this error:

    Send-isiAPI : The property 'errors' cannot be found on this object. Verify that the property exists.
        At IsilonPlatform\8.0.6\Functions\IsilonPlatformSet.ps1:5099 char:1
        8
        + ... ISIObject = Send-isiAPI -Method PUT -Resource "/platform/1/cluster/ow ...
        +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + CategoryInfo          : NotSpecified: (:) [Send-isiAPI], PropertyNotFoundException
            + FullyQualifiedErrorId : PropertyNotFoundStrict,Send-isiAPI

(The `PropertyNotFoundStrict` error is a result of using Set-StrictMode.)

**Comment by jcardel** [comment]
After upgrading cluster to 8.1.0.4, from 8.0.0.6, I get this error every time i try and use this module against this cluster.
like:
Get-isiJobs -Cluster xxxxx.uni.au.dk
The property 'errors' cannot be found on this object. Verify that the property exists.
    + CategoryInfo          : NotSpecified: (:) [Send-isiAPI], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Send-isiAPI

Doing it more basic, gives me:
```
$sessi = (Get-isiSession -Cluster xxxxx).session

Invoke-RestMethod "https://xxxxx:8080/platform/1/cluster/statfs" -Method GET -UseBasicParsing -WebSession $sessi
```
response:
```
Invoke-RestMethod : {"errors":[{"message":"authorization required"}]}
At line:1 char:1
+ Invoke-RestMethod "https://xxxxx.uni.au.dk:8080/platform/1/cluster/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```
This works without issues on a cluster with 8.1.0.2, so i wonder what they changed to make it crap like this. As you can see, i have no issue establishing the session.

Does anyone have a clue as to what can be the course?

**Comment by jcardel** [comment]
It looks like, adding the CRF header fix, removes this problem.

**Comment by cohizzle86** [comment]
> It looks like, adding the CRF header fix, removes this problem.

I am failing to understand what you did to make it work? I am running into the same issue with an 8.1.0.4 cluster.

**Comment by snordog** [comment]
Has there been any movement on this issue? I am running into the same issue. We were on 8.1.x and upgraded to 8.2.x and I am still receiving the same error. I am able to create a session, but from there, any command I issue (such as Get-isiShares) returns the above error.

**Comment by vchrisb** [comment]
Hi @snordog ,

Sorry, I'm not actively developing this since quite a while.
But I did merge a pull request a year ago which has the CSRF fix included.
As mentioned above, I haven't updated Isilon-POSH on PowershellGallery, but if you download it here from Github, you might get along.
If there is a different issue and someone is willing to to a PR, I'm happy to merge it.

**Comment by snordog** [comment]
@vchrisb I appreciate the quick response. I will definitely try the Github version and see how that goes. Thank you!

**Comment by rviglsf** [comment]
@vchrisb still getting the same error with the latest release 8.0.7 - I got it working with the following change in Send-IsiAPI but I cannot seem to have permissions to create a branch and send a PR. Anyway this is the code change to make:

                    if ($responseBody.errors) {
                        $responeMessage = $responseBody.errors.message | Out-String
                        Write-Error $responeMessage
                    }
