### ISSUE TITLE
s/UserName,Password/Credential

### ISSUE THREAD

**Issue by RamblingCookieMonster** [vchrisb/Isilon-POSH#2]
Nice looking module, looks great!

One small suggestion; it's a bit of a best practice to provide a Credential parameter in place of plaintext username and password parameters.

* Plain text parameters result in plain text passwords in your history, and Event Logs, if you enable logging.
* The Credential parameter is common across PowerShell Cmdlets which access credentials.  Similar to how using ComputerName is preferred over Computer, Server, or Host
* The Credential parameter works seamlessly with [DPAPI based credential serialization techniques](https://ramblingcookiemonster.wordpress.com/2014/11/27/quick-hits-credentials-and-dynamic-parameters/)
* It's simple to implement; a [PSCredential]$Credential parameter, and $Credential.UserName and $Credential.GetNetworkCredential().Password gets you what you need inside the function.

Let me know if you agree and would take a pull request, would be happy to submit one : )

Cheers!

**Comment by vchrisb** [comment]
Thx! :)
I only thought about not passing the password with each cmdlet. Therfore I use the websession cookie with invoke-webrequest.
But I didn't consider that passing the password in cleartext isn't a good thing at all.

Getting a pull request would be cool and my first one! :)

Cheers
