### ISSUE TITLE
Implement CSRF support (EMC Article 000517421)

### ISSUE THREAD

**Issue by ryanph** [vchrisb/Isilon-POSH#20]
When CSRF headers are not present (but CSRF is enabled on the API side) the cluster responds with 401 errors. Will affect anyone who installs EMC patch-213278.

**Comment by jcardel** [comment]
This was ultimately what I had problems with. Really to bad they did not mention this in the release notes, not so easy to troubleshoot imho.
Thanks for the fix!

**Comment by vchrisb** [comment]
looks like the change is working. I do not have the possibilities to test though. Still going to merge.
