### ISSUE TITLE
Remove isi-session does not work if session is timed out

### ISSUE THREAD

**Issue by sluetze** [vchrisb/Isilon-POSH#4]
if you pause your actions and the session expires you get the (expected) error:
Send-isiAPI : Session timout for "Cluster"

If you want to Remove the session by using Remove-isiSession -Cluster <cluster> I also get a timeout error. I guess this is because of the "send-isiAPI" Call to delete the session on the cluster.

so if you ran into the first timeout you are unable to connect to the cluster or remove the session until you restarted your powershell - session.

This may not be relevant if you only use the Module to automate, but if you want to administrate your cluster from a Windows Server

**Comment by vchrisb** [comment]
I've done quite a bit bug fixing and hardening of the functions the last days. I'll check if this also fixed and will probably commit the changes the next days.
You can also just reconnect using `New-isiSession`. That overwrites the expired session.

**Comment by vchrisb** [comment]
With my latest commit should the functions around the Session handling be more robust.
