### ISSUE TITLE
Send-isiAPI : The property 'Response' cannot be found on this object.

### ISSUE THREAD

**Issue by slientnight** [vchrisb/Isilon-POSH#6]
I just started seeing is error a few days ago.  Before that everything had been working well. 

get-isiSnapshots
Send-isiAPI : The property 'Response' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\IsilonPlatform\Functions\IsilonPlatformGet.ps1:6815 char:17
+ ... ISIObject = Send-isiAPI -Method GET -Resource ("/platform/1/snapshot/ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Send-isiAPI], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Send-isiAPI

PS C:\Users\hollisma> get-isiQuotas
Send-isiAPI : The property 'Response' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\IsilonPlatform\Functions\IsilonPlatformGet.ps1:5535 char:17
+ ... ISIObject = Send-isiAPI -Method GET -Resource ("/platform/1/quota/quo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Send-isiAPI], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Send-isiAPI

**Comment by vchrisb** [comment]
Which Isilon version and which Isilon-POSH version are you using?

**Comment by slientnight** [comment]
Sorry for the false error report.  This morning I deleted Isilon-POSH and used the latest version, and got more info from the error message. I don't use IE much so with the error talking about the first launch config I tried to open IE and it would not start.  Long story short our desktop group had an issue with EMET that was was breaking IE "iexplorer.exe Export Address Table Access Filtering"   which broke Invoke-RESTMethod. 
`Send-isiAPI : System.NotSupportedException: The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is 
not complete. Specify the UseBasicParsing parameter and try again. 
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.VerifyInternetExplorerAvailable(Boolean checkComObject)
   at Microsoft.PowerShell.Commands.InvokeWebRequestCommand.ProcessResponse(WebResponse response)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At C:\Program Files\WindowsPowerShell\Modules\IsilonPlatform\Functions\IsilonPlatformGet.ps1:13117 char:17
+ ... ISIObject = Send-isiAPI -Method GET -Resource ("/platform/1/quota/quo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Send-isiAPI`
