### ISSUE TITLE
Not properly sanitizing $BoundParameters before converting to JSON and sending in request body

### ISSUE THREAD

**Issue by devblackops** [vchrisb/Isilon-POSH#7]
In your functions, you are taking `$PSBoundParameters` and converting it to a JSON string then sending it to the API. This causes unneeded properties to be sent with the request when the function is called with common parameters such as `-Verbose` or `-Debug`. The Isilon API responds with an error when these properties are sent.

Might I suggest you sanitize your properties before sending to the API? The function below will remove common properties.

```powershell
function SanitizeBoundParameters {
	[cmdletbinding()]
	param(
		[parameter(Mandatory, ValueFromPipeline)]
		[hashtable]$Parameters
	)

	$commonParameters = @('Verbose', 'Debug', 'ErrorAction', 'ErrorVariable', 'WarningAction', 'WarningVariable',
		'OutBuffer', 'PipelineVariable', 'OutVariable')
	
	$commonParameters | % {
		$Parameters.Remove($_)
	}

	return $Parameters
}
```

This function could then be called like so:

```powershell
$boundParameters = $PSBoundParameters | SanitizeBoundParameters
$body = ConvertTo-Json -Depth 40 $BoundParameters
$ISIObject = Send-isiAPI -Method POST -Resource ("/platform/1/quota/quotas" + "$queryArguments") -body $body -Cluster $Cluster
```

**Comment by vchrisb** [comment]
Great!
I'll work the enhancement into [Isilon-POSH-Generator](https://github.com/vchrisb/Isilon-POSH-Generator) and recreate all functions.

**Comment by vchrisb** [comment]
merged enhancement with [Sanitize BoundParameters](https://github.com/vchrisb/Isilon-POSH/commit/0eab256e48560f9538c80926cf505f067ef414b1)
