### ISSUE TITLE
Error using -Force parameter with Set-IsiSnapshot

### ISSUE THREAD

**Issue by hershsa** [vchrisb/Isilon-POSH#9]
Trying to change the expiration of snapshot without being prompted by using the -force option but receiving the following error:

Send-isiAPI : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\IsilonPlatform\Functions\IsilonPlatformSet.ps1:9870 char:18
+                 $ISIObject = Send-isiAPI -Method PUT -Resource "/platform/1/snapshot/snapsho ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Send-isiAPI], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Send-isiAPI

Command I'm using (which works without the -force):

Set-isiSnapshot -id $snapshot.id -expires $new_expiration -Force

**Comment by vchrisb** [comment]
Thank you for reporting the bug!

There are actually two bugs:
* correctly handling an Isilon response with multiple errors
* `Force` among others is missing in the `SanitizeBoundParameters` function

I'll fix them and commit the changes

**Comment by vchrisb** [comment]
I fixed these issues with this commit: 97f1dc7f9dfa7ab421dce8c710c11f1c4dff2103
@hershsa can you please test it?

**Comment by hershsa** [comment]
That did the trick! Thanks for the quick fix.

**Comment by vchrisb** [comment]
Great! I'm creating a new release.
